-- Keyboard Warrior Battle Royale
-- Supabase SQL Editor paste-ready schema
--
-- Principle:
-- - Keep the teammate-provided ERD as intact as possible
-- - Apply only the minimum PostgreSQL/Supabase fixes needed to run
--
-- Minimal compatibility adjustments:
-- 1. users.id is uuid, so participants.user_id is also created as uuid
-- 2. token hash -> text
-- 3. created_at now -> timestamptz default now()
-- 4. updated_at integer -> bigint
-- 5. Forward references are resolved by table creation order

create extension if not exists "pgcrypto";

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  nickname varchar(50) not null unique,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_stats (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.users(id) on delete cascade,
  total_games integer not null default 0,
  wins integer not null default 0,
  wpm integer not null default 0,
  avg_rank integer not null default 0,
  best_rank integer not null default 0,
  recent_rank integer not null default 0,
  world_rank integer not null default 0,
  accuracy integer not null default 0,
  top_percentile integer not null default 0,
  total_play_count integer not null default 0,
  avg_word_count integer not null default 0,
  recent_word_count integer not null default 0,
  total_word_count integer not null default 0,
  updated_at bigint
);

create table if not exists public.refresh_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.users(id) on delete cascade,
  token text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.prompts (
  id bigint generated by default as identity primary key,
  slug varchar(50) not null unique,
  title varchar(100) not null,
  content text not null,
  content_length integer generated always as (char_length(content)) stored,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  check (char_length(content) in (500, 750, 900, 1000, 1250))
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  status boolean not null default false,
  started_at varchar(255),
  ended_at varchar(255),
  total_players varchar(255),
  winner_user_id text,
  prompt_id bigint references public.prompts(id) on delete set null
);

create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  status boolean not null default false,
  started_at varchar(255),
  ended_at varchar(255),
  total_players varchar(255),
  winner_user_id text
);

create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  chat_id bigint references public.chats(id) on delete set null,
  user_id uuid not null references public.users(id) on delete cascade,
  final_rank integer,
  is_winner boolean not null default false,
  is_suvived boolean not null default false,
  life integer not null default 0,
  wpm integer not null default 0,
  accuracy integer not null default 0,
  created_at date not null default current_date
);

create index if not exists idx_users_created_at on public.users(created_at);
create index if not exists idx_prompts_is_active on public.prompts(is_active);
create index if not exists idx_games_status on public.games(status);
create index if not exists idx_chats_status on public.chats(status);
create index if not exists idx_participants_game_id on public.participants(game_id);
create index if not exists idx_participants_user_id on public.participants(user_id);

comment on table public.users is 'Anonymous user profile table';
comment on table public.user_stats is 'Aggregated dashboard stats per user';
comment on table public.refresh_tokens is 'Refresh token storage';
comment on table public.prompts is 'Typing prompt source texts';
comment on table public.games is 'Game round metadata';
comment on table public.chats is 'Chat room or session metadata from original ERD';
comment on table public.participants is 'Participant result table from original ERD';

comment on column public.prompts.content_length is 'Calculated character length for the stored Korean typing prompt';
comment on column public.participants.game_id is 'Many participant result rows can belong to the same game';
comment on column public.participants.chat_id is 'Optional chat session reference';
comment on column public.participants.user_id is 'Changed from integer to uuid to match users.id; one user can have many game result rows';
comment on column public.participants.is_suvived is 'Column name preserved from original ERD spelling';

insert into public.prompts (slug, title, content)
values
  (
    'market-morning-500',
    '시장 골목의 아침',
    '이른 아침 시장 골목에 들어서면 아직 해가 완전히 오르지 않았는데도 가게마다 분주한 기척이 번진다. 채소를 다듬는 손끝에서는 물기가 반짝이고, 갓 구운 빵을 진열하는 사람은 따뜻한 김이 식기 전에 손님이 오기를 기다린다. 골목 끝 국밥집에서는 사골 냄새가 천천히 퍼져 지나가는 사람들의 발걸음을 붙잡고, 꽃가게 앞 양동이에는 계절이 바뀔 때마다 다른 빛의 색이 담긴다. 시장은 화려한 구호보다 익숙한 인사로 하루를 시작한다. 단골은 무게를 재기 전부터 값을 짐작하고, 주인은 비닐봉지보다 먼저 안부를 건넨다. 바쁜 척 스쳐 가는 사람도 많지만, 자세히 보면 모두가 잠깐씩 서로의 하루를 밀어 주고 있다. 누군가는 아이가 좋아하는 반찬거리를 고르고, 누군가는 오늘 처음 문을 연 가게 앞에서 조심스럽게 메뉴판을 읽는다. 그렇게 작은 선택과 짧은 대화가 쌓이면 시장은 단순히 물건을 사고파는 장소를 넘어, 동네의 시간과 표정을 고스란히 품은 생활의 중심이 된다. 오늘도 그 골목은 열리고 숨 쉰다.'
  ),
  (
    'city-before-rain-750',
    '비 오기 전 도시',
    '비가 내리기 전의 도시는 늘 조금 다른 목소리를 낸다. 아스팔트 위를 달리던 자동차 소리는 평소보다 낮아지고, 횡단보도 앞에 선 사람들은 하늘을 한 번 더 올려다본다. 구름은 금방이라도 비를 쏟아 낼 듯 무거워 보이지만, 그 짧은 틈에 거리에는 이상하리만큼 선명한 냄새가 감돈다. 빵집 문이 열릴 때마다 버터 향이 젖은 공기와 섞이고, 카페 앞 화분에서는 흙 냄새가 먼저 올라온다. 이런 날이면 사람들의 걸음에도 미묘한 망설임이 생긴다. 서둘러 목적지로 향하면서도 우산을 펼쳐야 할 순간을 계산하느라 발끝이 잠깐 늦어진다. 그러나 빗방울이 실제로 떨어지기 시작하면 오히려 풍경은 단정해진다. 각자의 우산 아래로 작고 또렷한 경계가 생기고, 사람들은 그 안에서 자신만의 속도로 움직인다. 편의점 처마 아래 잠시 비를 피하는 학생들, 택시를 잡으려 손을 드는 직장인, 젖은 간판을 닦으며 웃는 가게 주인까지 모두가 같은 날씨를 지나지만 저마다 다른 하루를 산다. 나는 그런 장면을 볼 때마다 도시가 거대한 기계처럼 움직이는 곳이 아니라, 수많은 사소한 선택과 감정이 겹쳐서 간신히 유지되는 생활의 집합이라는 사실을 떠올린다. 비는 불편을 주기도 하지만, 동시에 우리가 익숙함 속에서 지나치던 것들을 다시 보게 만든다. 평소에는 빠르게 지나쳤을 골목의 깊이, 빗물에 비친 신호등의 색, 젖은 신발을 털며 서로를 바라보는 순간의 표정 같은 것들 말이다. 그 짧은 멈춤 덕분에 사람들은 같은 거리도 조금 다르게 기억하게 된다. 여운은 천천히 남는다.'
  ),
  (
    'library-night-900',
    '늦은 밤의 도서관',
    '도서관은 조용한 장소라고들 말하지만, 오래 머물러 보면 그 안에는 생각보다 많은 종류의 소리가 흐른다. 의자가 바닥을 스치는 마른 마찰음, 페이지가 넘어가는 가벼운 숨결, 형광펜 뚜껑을 여닫는 작은 박자, 창가 자리에 앉은 사람이 집중을 풀며 길게 내쉬는 한숨까지 모두 저마다 다른 결을 지닌다. 그 소리들은 서로를 방해하지 않을 만큼만 존재하면서 이상하게도 공간 전체를 단단하게 묶어 준다. 시험 기간이 가까워지면 열람실의 공기는 눈에 보이지 않을 정도로 팽팽해진다. 누군가는 두꺼운 전공서를 쌓아 두고 밑줄을 그으며 읽고, 누군가는 노트북 화면을 응시한 채 좀처럼 진도를 나가지 못한다. 어떤 사람은 잠깐 복도로 나와 자판기 커피를 마시고 다시 돌아가고, 어떤 사람은 창밖 나무의 흔들림을 오래 바라보다가 조용히 책장으로 향한다. 그 모습들을 보고 있으면 공부란 결국 남과 비교해 속도를 올리는 일이 아니라, 흔들리는 마음을 데리고 제 자리로 여러 번 돌아오는 연습에 가깝다는 생각이 든다. 도서관이 필요한 이유도 거기에 있다. 이곳은 특별한 해답을 직접 건네주지 않지만, 적어도 포기하지 않도록 분위기를 만들어 준다. 모두가 같은 방향을 보고 있다는 사실 하나만으로도 사람은 조금 더 버틸 힘을 얻는다. 늦은 밤 마지막 안내 방송이 나오면 사람들은 아쉬운 표정으로 책을 덮고 짐을 챙긴다. 그러나 그들이 들고 나가는 것은 단순한 메모와 자료만이 아니다. 오늘도 끝까지 자리를 지켰다는 감각, 이해되지 않던 문장을 결국 다시 읽어 냈다는 작지만 분명한 성취, 그리고 내일도 다시 시작할 수 있다는 희미하지만 필요한 자신감이 함께 따라나간다. 한 페이지를 더 읽은 밤은 다음 날의 마음가짐까지 바꾸어 놓는다. 그래서 도서관의 밤은 끝나는 것이 아니라, 각자의 내일 속으로 조금씩 옮겨 가는 중인지도 모른다.'
  ),
  (
    'winter-harbor-1000',
    '겨울 항구의 하루',
    '바닷가 마을의 겨울은 생각보다 조용하지 않다. 관광객이 줄어든 거리에는 한산함이 남지만, 새벽마다 항구로 모여드는 사람들의 움직임은 오히려 더 선명하게 드러난다. 아직 어둠이 걷히기 전 부두에 서 있으면 밧줄이 물기 머금은 나무 난간을 두드리는 소리와, 작업복 위에 두툼한 외투를 걸친 사람들이 서로의 안부를 묻는 목소리가 차가운 공기를 가른다. 배에서 막 내려온 생선 상자에서는 바다 냄새가 짙게 올라오고, 경매를 준비하는 손놀림은 추위를 잊은 듯 빠르고 정확하다. 해가 조금씩 떠오르면 수평선은 잿빛에서 옅은 금빛으로 바뀌고, 그 빛이 젖은 바닥과 스테인리스 양동이에 반사되어 항구 전체가 잠시 환해진다. 마을 사람들은 그 짧은 순간을 특별하다고 말하지 않지만, 오랫동안 같은 풍경을 본 사람일수록 그 미묘한 변화가 하루의 기분을 정한다는 사실을 알고 있다. 점심 무렵이 되면 골목 안쪽 작은 식당들에 김이 오른다. 이른 아침 일을 마친 사람들이 국을 앞에 두고 앉아 말없이 수저를 들다가도, 어느새 오늘 파도가 어땠는지, 물때가 얼마나 달라졌는지, 올해는 어느 어종이 유난히 늦는지 같은 이야기를 자연스럽게 꺼낸다. 그 대화는 거창한 계획으로 이어지지 않아도 서로의 생활을 튼튼하게 잇는 밧줄처럼 기능한다. 오후의 마을은 다시 느긋해 보이지만, 그것은 일이 끝나서가 아니라 각자의 자리에서 다음 시간을 준비하기 때문이다. 누군가는 그물을 손질하고, 누군가는 깨진 상자를 고치고, 누군가는 창고 문을 열어 내일 쓸 장비를 점검한다. 바람이 거세게 부는 날에도 사람들은 쉬이 불평하지 않는다. 대신 날씨가 허락하는 범위 안에서 할 수 있는 일을 찾고, 하지 못한 일은 다음 차례로 미룬다. 그래서 이 마을의 겨울은 멈춘 계절이 아니라, 보이지 않는 인내와 반복으로 천천히 움직이는 시간처럼 느껴진다. 그 차분한 리듬이 결국 겨울 바다 앞의 삶을 오래 지탱한다. 해가 완전히 저문 뒤에도 마을의 불빛은 서로의 자리를 확인하듯 차례로 켜지고, 그 장면은 긴 하루의 끝을 조용히 붙들어 준다'
  ),
  (
    'night-train-1250',
    '야간 열차의 새벽',
    '늦은 밤 출발한 열차 안에서는 낮 동안 미처 정리하지 못한 생각들이 이상하리만큼 또렷해진다. 창밖은 이미 깊은 어둠 속으로 잠겨 있지만, 가끔씩 이름 모를 역을 스쳐 갈 때마다 플랫폼의 형광등이 객실 창에 잠깐 번져 승객들의 얼굴을 비춘다. 그 짧은 빛 속에서 누군가는 이어폰을 고쳐 끼우고, 누군가는 무릎 위에 펼쳐 둔 책을 덮고, 누군가는 휴대전화 화면에 떠 있는 오래된 메시지를 한참 동안 내려다본다. 같은 칸에 앉아 있어도 각자가 품은 사정은 전혀 다르겠지만, 목적지를 향해 함께 흔들리고 있다는 사실만으로도 묘한 동료 의식이 생긴다. 나는 야간 열차를 탈 때마다 사람의 마음도 이런 객실과 비슷하다고 느낀다. 겉으로는 조용해 보여도 내부에는 미뤄 둔 결심, 다 말하지 못한 후회, 곧 시작해야 할 일에 대한 불안이 좌석마다 나누어 실려 있기 때문이다. 어떤 사람은 잠들어야 내일을 버틸 수 있다는 걸 알면서도 쉽게 눈을 감지 못하고, 어떤 사람은 창문에 비친 자신의 얼굴을 바라보다가 문득 오래전 여행의 장면을 떠올린다. 차창 너머로 보이는 어두운 논밭과 드문드문 켜진 마을 불빛은 지금 지나가는 시간이 분명 현실인데도 어딘가 꿈처럼 느껴지게 만든다. 그래서 야간 열차는 단순한 이동 수단을 넘어, 잠시 동안 현재의 삶에서 비켜 서서 자신을 들여다보게 하는 기다란 복도 같은 역할을 한다. 객실 끝 연결문이 열릴 때마다 찬 공기가 스며들고, 복도를 지나는 승무원의 발걸음이 바닥을 규칙적으로 울리면 사람들은 다시 제 몸을 추스른다. 몸을 의자에 기대고 담요를 끌어올리는 작은 동작에도 각자의 피로가 배어 있다. 아침이 되면 새로운 도시에 도착한다는 기대, 그곳에서 누군가를 다시 만나거나 전혀 다른 풍경을 보게 되리라는 예감도 분명 함께 실려 있다. 결국 여행은 멀리 가는 일만이 아니라, 지금의 자신에게서 잠시 거리를 확보하는 일이기도 하다. 익숙한 장소에서는 같은 생각만 맴돌던 사람도 낯선 방향으로 달리는 열차 안에서는 예상하지 못한 질문을 스스로에게 던지게 된다. 내가 정말 원하는 생활은 무엇인지, 그동안 붙잡고 있던 계획이 아직도 유효한지, 반복되는 하루 속에서 놓치고 있는 감정은 없는지 같은 질문들이다. 물론 모든 답이 그 자리에서 정리되지는 않는다. 다만 분명한 것은, 목적지에 내릴 무렵의 사람은 출발 직전의 사람과 완전히 같을 수 없다는 사실이다. 열차의 속도와 흔들림, 잠들지 못한 몇 시간, 스쳐 지나간 불빛과 침묵이 조금씩 마음의 모양을 바꾸어 놓기 때문이다. 그리하여 사람들은 다시 하루를 시작한다'
  )
on conflict (slug) do update
set
  title = excluded.title,
  content = excluded.content,
  is_active = true;
