-- Keyboard Warrior Battle Royale
-- Supabase SQL Editor paste-ready schema
--
-- Principle:
-- - Keep the teammate-provided ERD as intact as possible
-- - Apply only the minimum PostgreSQL/Supabase fixes needed to run
--
-- Minimal compatibility adjustments:
-- 1. users.id is uuid, so participants.user_id is also created as uuid
-- 2. token hash -> text
-- 3. created_at now -> timestamptz default now()
-- 4. updated_at integer -> bigint
-- 5. Forward references are resolved by table creation order

create extension if not exists "pgcrypto";

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  nickname varchar(50) not null unique,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_stats (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.users(id) on delete cascade,
  total_games integer not null default 0,
  wins integer not null default 0,
  wpm integer not null default 0,
  avg_rank integer not null default 0,
  best_rank integer not null default 0,
  recent_rank integer not null default 0,
  world_rank integer not null default 0,
  accuracy integer not null default 0,
  top_percentile integer not null default 0,
  total_play_count integer not null default 0,
  avg_word_count integer not null default 0,
  recent_word_count integer not null default 0,
  total_word_count integer not null default 0,
  updated_at bigint
);

create table if not exists public.refresh_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.users(id) on delete cascade,
  token text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  status boolean not null default false,
  started_at varchar(255),
  ended_at varchar(255),
  total_players varchar(255),
  winner_user_id text
);

create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  status boolean not null default false,
  started_at varchar(255),
  ended_at varchar(255),
  total_players varchar(255),
  winner_user_id text
);

create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  game_id bigint unique references public.games(id) on delete cascade,
  chat_id bigint unique references public.chats(id) on delete set null,
  user_id uuid unique references public.users(id) on delete cascade,
  final_rank integer,
  is_winner boolean not null default false,
  is_suvived boolean not null default false,
  life integer not null default 0,
  wpm integer not null default 0,
  accuracy integer not null default 0,
  created_at date not null default current_date
);

create index if not exists idx_users_created_at on public.users(created_at);
create index if not exists idx_games_status on public.games(status);
create index if not exists idx_chats_status on public.chats(status);

comment on table public.users is 'Anonymous user profile table';
comment on table public.user_stats is 'Aggregated dashboard stats per user';
comment on table public.refresh_tokens is 'Refresh token storage';
comment on table public.games is 'Game round metadata';
comment on table public.chats is 'Chat room or session metadata from original ERD';
comment on table public.participants is 'Participant result table from original ERD';

comment on column public.participants.game_id is 'Original ERD keeps this unique; review later if one game should have many participants';
comment on column public.participants.chat_id is 'Original ERD keeps this unique; review later based on chat design';
comment on column public.participants.user_id is 'Changed from integer to uuid only to match users.id type';
comment on column public.participants.is_suvived is 'Column name preserved from original ERD spelling';
