export const SOCKET_EVENTS = {
  BATTLE_COUNTDOWN: "battle:countdown",
  BATTLE_ELIMINATED: "battle:eliminated",
  BATTLE_ERROR: "battle:error",
  BATTLE_FINISHED: "battle:finished",
  BATTLE_INPUT: "battle:input",
  BATTLE_INPUT_RESULT: "battle:input-result",
  BATTLE_JOIN: "battle:join",
  BATTLE_PROGRESS: "battle:progress",
  BATTLE_READY: "battle:ready",
  BATTLE_READY_CONFIRMED: "battle:ready-confirmed",
  BATTLE_PLAYER_READY: "battle:player-ready",
  BATTLE_SPECTATE: "battle:spectate",
  BATTLE_STARTED: "battle:started",
  BATTLE_STATE: "battle:state",
  BATTLE_WAITING: "battle:waiting",
  BATTLE_WELCOME: "battle:welcome",
} as const;
